### ISSUE TITLE
How to use the softlink to deal with the memory error?

### ISSUE THREAD

**Issue by Seal-CJH** [Jbwasse2/6D_Pose_Estimation#1]
Hi, I followed your steps to set up envrionment on cluster, but the **"OSError: [Errno 122] Disk quota exceeded" is annoying.**
I set up softlink by "ln -s ~/scratch/conda .conda"
and I checked that link. "lrwxrwxrwx 1 junhong7 sp20-ece549r1-eng 28 May  1 23:02 .conda -> /home/junhong7/scratch/conda"
I typed " conda create --name xx python=3.6" but I can't create a virtual env because of the memory issue. 

Can you give me some advice on how to solve this problem?

**Comment by Jbwasse2** [comment]
I took a look at your home directory on the cluster and it appears that your .conda is not a soft link, but is a directory. Perhaps you made the soft link in a directory that is not the home directory?

Try deleting .conda in your home directory, and create the soft link while in ~/ again.

For reference here is what your .conda looks like in your home directory
`
drwxrwsr-x    4 junhong7 sp20-ece549r1-eng   4096 May  5 12:56 .conda
`
and the following is mine
`
lrwxrwxrwx    1 jbwasse2 AUP1_0                  29 Apr  4 19:08 .conda -> /home/jbwasse2/scratch/conda/
`

**Comment by Seal-CJH** [comment]
thanks!!
I delete the ".conda" under ~/ and delete the conda file that I created before and create softlink again. 
It actually works!!! 
thanks agian!!

**Comment by Jbwasse2** [comment]
no problem
